all:
  children:
    webservers:
      hosts:
        172.31.26.196:
          package_name: ubuntu
          php_modules:
            - php
            - libapache2-mod-php
            - php-cli
        172.31.25.93:
          package_name: httpd
          php_modules:
            - php